### PR TITLE
update gemspec for rails 5

### PR DESCRIPTION
**Pull request by rakvat**
Could you please merge this code, which allows the gem to be used in Rails 5?

### CODE REVIEW

**Comment by rakvat** [comment]
I guess this requires to also increase `s.required_ruby_version = '~> 2.1'`

**Comment by 2called-chaos** [comment]
+1 (it's the only gem that prevents us from migrating to rails 5)

**Comment by javierjulio** [comment]
Why is this necessary for you? The rack requirement is just a development dependency. That would only be if you were developing/contributing to the gems' source. Its not applicable when you use the gem say in a Rails app.

I've been able to migrate to Rails 5 using this just fine but I have to install the gem from master. We'll have to ping the owners to do a new release with the change I did support that in #53.

**Comment by rakvat** [comment]
@javierjulio sorry for not getting back to you earlier. 
Using the master works for me. However, I would prefer to have an official gem version. Could you please create a release?

**Comment by javierjulio** [comment]
@rakvat I can't because I don't have access. I've asked @kleetus again on #53 to see if they can cut a version release of this update.

**Pull request merged**
